apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 5080
      targetPort: 5001
      nodePort: 30007
  type: NodePort
