apiVersion: v1
kind: Secret
metadata:
  name: nexus-secret
type: Opaque
data:
  username: admin
  password: Nitin@1234
[gslab@rhel8 k8s_app]$ cat service.yml 
apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 5080
      targetPort: 5001
      nodePort: 30007
  type: NodePort
